Repository SOPT-all/35-COLLABORATION-WEB-SKYSCANNER, pull requests merged in 2024-11, with the labels that each got.

#2 [ Init ] 초기 프로젝트 생성
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  public/Logo.png
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ init

#5 [ Init ] 절대 경로 설정
  src/main.tsx
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️ init

#8 [ Init ] Prettier, ESLint 설정
  .eslintrc.cjs
  .prettierrc
  eslint.config.js
  package.json
  src/App.tsx
  src/main.tsx
  vite.config.ts
  yarn.lock
Labels: ⚙️ init

#12 [ init ] svg 설정
  package.json
  src/svg.d.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ init

#15 [ Feat ] Footer Component
  src/App.tsx
  src/Layout.tsx
  src/assets/svg/ic_android.svg
  src/assets/svg/ic_angle_down_white.svg
  src/components/common/Footer.tsx
  src/styles/GlobalStyle.ts
  src/styles/styles.d.ts
  src/styles/theme.ts
Labels: 🏠 common, :sparkles: feat

#17 [ Feat ] Header 구현
  src/App.tsx
  src/Layout.tsx
  src/Router.tsx
  src/assets/svg/.gitkeep
  src/assets/svg/ic_car_white.svg
  src/assets/svg/ic_flag_korea.svg
  src/assets/svg/ic_flight_white.svg
  src/assets/svg/ic_hotel_white.svg
  src/assets/svg/ic_likepage.svg
  src/assets/svg/ic_mainolgo_white.svg
  src/assets/svg/ic_my.svg
  src/assets/svg/ic_skyscanner_logo.svg
  src/assets/svg/index.ts
  src/components/common/FilterButton.tsx
  src/components/common/Header.tsx
  src/pages/home/index.tsx
  src/pages/reservation/index.tsx
  src/router/Router.tsx
  src/router/path.ts
  src/styles/theme.ts
  vite.config.ts
Labels: 🏠 common, :sparkles: feat

#23 [ Feat ] Tab 컴포넌트 구현
  src/components/wish/.gitkeep
  src/components/wish/Tab.tsx
  src/pages/wish/Wish.tsx
  src/pages/wish/index.tsx
  src/router/Router.tsx
  src/styles/theme.ts
Labels: :sparkles: feat

#21 [ feat ] 가격 기준 정보 모달 구현
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/home/calender-modal.tsx
  src/components/home/price-image.tsx
  src/components/home/price-modal.tsx
  src/pages/home/index.tsx
  src/styles/customStyle.ts
Labels: 🏠 common, :sparkles: feat

#29 [ Feat ] Wish 페이지 아티클 컴포넌트 구현
  src/assets/svg/ic_exclamation.svg
  src/assets/svg/ic_jejuair.svg
  src/assets/svg/ic_like_blue.svg
  src/components/wish/FlightDetails.tsx
  src/components/wish/FlightInfo.tsx
  src/components/wish/Tab.tsx
  src/components/wish/ToggleSwitch.tsx
  src/components/wish/WishContentCard.tsx
  src/components/wish/WishContents.tsx
  src/mocks/mockWishList.ts
  src/pages/wish/Wish.tsx
  src/router/Router.tsx
  src/types/wishContentCard.ts
Labels: :sparkles: feat

#36 [ Feat ] 위시리스트 호텔 아티클 컴포넌트 구현
  src/assets/img/.gitkeep
  src/assets/img/hotel1.png
  src/assets/img/hotel2.png
  src/assets/img/hotel3.png
  src/assets/img/hotel4.png
  src/assets/img/hotel5.png
  src/assets/img/hotel6.png
  src/assets/svg/ic_Score.svg
  src/assets/svg/ic_advisor.svg
  src/assets/svg/ic_star.svg
  src/components/wish/ToggleSwitch.tsx
  src/components/wish/WishAirplaneContents.tsx
  src/components/wish/WishContentCard.tsx
  src/components/wish/WishContents.tsx
  src/components/wish/WishHotelContentCard.tsx
  src/components/wish/WishHotelContents.tsx
  src/mocks/hotelData.ts
  src/pages/wish/Wish.tsx
  src/types/WishHotelContentCardProps.ts
Labels: :sparkles: feat

#34 [ Feat ] home 페이지 검색창 구현
  src/assets/svg/ic_calendar_grey.svg
  src/assets/svg/ic_check_round_fill.svg
  src/assets/svg/ic_check_round_navy.svg
  src/assets/svg/ic_check_square.svg
  src/assets/svg/ic_check_square_filled.svg
  src/assets/svg/ic_close.svg
  src/assets/svg/ic_minus_circle.svg
  src/assets/svg/ic_minus_circle_unfilled.svg
  src/assets/svg/ic_origin.svg
  src/assets/svg/ic_pin.svg
  src/assets/svg/ic_plus_circle.svg
  src/assets/svg/ic_profile.svg
  src/assets/svg/index.ts
  src/components/common/Button.tsx
  src/components/home/Search.tsx
  src/components/home/SearchBottom.tsx
  src/components/home/SearchCalendarWrapper.tsx
  src/components/home/SearchCheckedBox.tsx
  src/components/home/SearchClickedFieldWrapper.tsx
  src/components/home/SearchRadioButton.tsx
  src/components/home/SearchTextField.tsx
  src/pages/home/home.tsx
  src/router/Router.tsx
  src/styles/GlobalStyle.ts
  yarn.lock
Labels: :sparkles: feat

#38 [ Feat ] home 페이지 내 추천 카드 구현
  src/components/home/RecommendCard.tsx
  src/mocks/mockRecommendList.ts
  src/types/recommendCard.ts
Labels: :sparkles: feat

#31 [ Feat ] 항공권 컴포넌트 퍼블리싱
  src/assets/svg/ic_ arrow_drop_down.svg
  src/assets/svg/ic_arrow_right_white.svg
  src/assets/svg/ic_exclamation_circle_navy.svg
  src/assets/svg/ic_heart_black.svg
  src/assets/svg/ic_heat_outline.svg
  src/assets/svg/img_eastar.svg
  src/assets/svg/img_jejuair.svg
  src/assets/svg/img_jinair.svg
  src/assets/svg/img_koreaair.svg
  src/assets/svg/img_tway.svg
  src/assets/svg/index.ts
  src/components/reservation/FlightCard.tsx
  src/components/reservation/FlightList.tsx
  src/components/reservation/Icons.tsx
  src/components/reservation/Info.tsx
  src/components/reservation/PriceSelect.tsx
  src/styles/theme.ts
Labels: :sparkles: feat

#43 [ fix ] svg 네이밍 오류 수정
  src/assets/svg/index.ts
Labels: 🐞fix

#25 [ feat ] 검색 필터 모달 퍼블리싱
  src/assets/svg/ic_arrow_left_black_new.svg
  src/assets/svg/ic_flight_grey.svg
  src/assets/svg/index.ts
  src/components/common/Button.tsx
  src/components/common/InputForm.tsx
  src/components/home/CalenderModal.tsx
  src/components/home/CityGroup.tsx
  src/components/home/PriceImage.tsx
  src/components/home/PriceModal.tsx
  src/components/home/Search.tsx
  src/components/home/SearchModal.tsx
  src/constants/cityGroups.ts
  src/hooks/useModal.ts
  src/pages/home/home.tsx
  src/styles/customStyle.ts
Labels: :sparkles: feat

#45 [ Api ] 위시리스트 api 연결
  .gitignore
  package.json
  src/api/.gitkeep
  src/api/wish/getWishList.ts
  src/assets/svg/index.ts
  src/components/common/Button.tsx
  src/components/home/RecommendCard.tsx
  src/components/reservation/Adcard.tsx
  src/components/reservation/FlightCard.tsx
  src/components/reservation/HotelList.tsx
  src/components/wish/FlightInfo.tsx
  src/components/wish/WishAirplaneContents.tsx
  src/components/wish/WishHotelContents.tsx
  src/hooks/.gitkeep
  src/hooks/useWishList.ts
  src/libs/.gitkeep
  src/libs/api.ts
  src/main.tsx
  src/mocks/mockHotelData.ts
  src/styles/.gitkeep
  src/styles/GlobalStyle.ts
  src/styles/reset.ts
  src/styles/theme.ts
  src/svg.d.ts
  yarn.lock
Labels: 🚀api

#46 [ Feat ] 렌터카 섹션 퍼블리싱
  src/assets/svg/ic_bag.svg
  src/assets/svg/ic_cardoor.svg
  src/assets/svg/ic_heart.svg
  src/assets/svg/ic_heart_black.svg
  src/assets/svg/ic_heart_outline.svg
  src/assets/svg/ic_profile_black.svg
  src/assets/svg/img_car.svg
  src/assets/svg/index.ts
  src/components/reservation/Adcard.tsx
  src/components/reservation/Car.tsx
  src/components/reservation/FlightCard.tsx
  src/components/reservation/Hotel.tsx
  src/components/reservation/HotelCard.tsx
  src/components/reservation/Icons.tsx
  src/components/reservation/PriceSelect.tsx
  src/hooks/useFlights.ts
  src/pages/reservation/Reservation.tsx
Labels: :sparkles: feat

#54 [ Api ] home 내 추천 카드 api 연결 작업
  src/api/recommend/getRecommendList.ts
  src/assets/svg/index.ts
  src/components/home/HomeContents.tsx
  src/components/reservation/Icons.tsx
  src/hooks/useRecommendList.ts
Labels: 🚀api

#49 [ Feat] 캘린더 모달 구현
  eslint.config.js
  package.json
  src/assets/svg/ic_arrow_right_black_new.svg
  src/assets/svg/ic_autornew_white.svg
  src/assets/svg/index.ts
  src/components/common/Button.tsx
  src/components/home/.gitkeep
  src/components/home/Calender.ts
  src/components/home/Calender.tsx
  src/components/home/CalenderModal.tsx
  src/components/home/PriceImage.tsx
  src/components/home/PriceInfoItem.tsx
  src/components/home/PriceModal.tsx
  src/components/home/SearchModal.tsx
  src/mock/mockCalenderData.ts
  src/pages/calender/CalenderModal.tsx
  src/pages/home/home.tsx
  src/pages/reservation/Reservation.tsx
  src/router/Router.tsx
  src/router/path.ts
  src/styles/GlobalStyle.ts
  src/utils/dateHandler.ts
Labels: 🏠 common, :sparkles: feat

#56 [ Api ] Reservation 페이지 api 연결 작업
  src/api/reservation/getFlights.ts
  src/api/reservation/patchWisiList.ts
  src/components/reservation/FlightCard.tsx
  src/components/reservation/FlightList.tsx
  src/components/reservation/Icons.tsx
  src/components/reservation/Info.tsx
  src/components/reservation/PriceSelect.tsx
  src/components/reservation/TabFlight.tsx
  src/hooks/useFlights.ts
  src/libs/api.ts
  src/pages/reservation/Reservation.tsx
  src/types/FlightTypes.ts
  src/utils/flightUtils.ts
Labels: 🚀api

#64 [ Feat ] Home <-> Reservation 간 날짜 연동
  src/components/home/Search.tsx
  src/components/reservation/DateFilter.tsx
  src/pages/reservation/Reservation.tsx
Labels: :sparkles: feat

#62 [ Feat ] 무한 스크롤 구현
  src/components/reservation/FlightCard.tsx
  src/components/reservation/FlightList.tsx
  src/components/reservation/Hotel.tsx
  src/hooks/useFlights.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/reservation/Reservation.tsx
Labels: :sparkles: feat

#65 [ Feat ] 성능 최적화
  src/Layout.tsx
  src/components/common/.gitkeep
  src/components/common/WithSuspense.tsx
  src/components/home/RecommendCard.tsx
  src/components/reservation/.gitkeep
  src/components/wish/WishAirplaneContentCard.tsx
  src/components/wish/WishAirplaneContents.tsx
  src/components/wish/WishContents.tsx
  src/components/wish/WishHotelContentCard.tsx
  src/hooks/useWishList.ts
  src/types/wishAirplaneContentCard.ts
Labels: :sparkles: feat

#69 [ Fix ] svg 이름 수정
  src/assets/svg/ic_score1.svg
  src/components/wish/WishHotelContentCard.tsx
  vercel.json
Labels: 🐞fix

#72 [ feat ] build.sh 파일 추가
  .github/workflows/deploy.yml
  build.sh
Labels: :sparkles: feat

#73 [ Fix ] deploy 수정
  .github/workflows/deploy.yml
Labels: 🐞fix

#74 [ Fix ] target-branch 변경
  .github/workflows/deploy.yml
Labels: 🐞fix

#75 [ Feat ] 이미지 성능 최적화
  src/assets/img/img_car.png
  src/assets/img/img_cardboard.png
  src/assets/svg/cardboard.svg
  src/assets/svg/ic_advisor.svg
  src/assets/svg/img_car.svg
  src/assets/svg/img_jejuair.svg
  src/assets/svg/index.ts
  src/components/home/HomeContents.tsx
  src/components/reservation/Car.tsx
  src/components/wish/WishAirplaneContentCard.tsx
  src/components/wish/WishHotelContentCard.tsx
Labels: :sparkles: feat

#79 [ Fix ] png파일 이미지 경로 수정
  src/components/home/HomeContents.tsx
  src/components/reservation/Car.tsx
Labels: 🐞fix
